name: CI/CD for Windows IIS Container

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Login (PowerShell)
      run: |
        echo $Env:DOCKER_PASSWORD | docker login -u $Env:DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/welcome_page:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/welcome_page:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy latest image to Windows EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          powershell -Command "
            try {
              # Ensure log directory exists
              New-Item -ItemType Directory -Path C:\users\administrator\logs -Force | Out-Null

              Add-Content -Path C:\users\administrator\logs\deploy_log.txt -Value ('[INFO] Deployment started at ' + (Get-Date))

              Write-Host 'Stopping existing container...'
              docker stop welcome_page | Out-File -Append -FilePath C:\users\administrator\logs\deploy_log.txt

              Write-Host 'Removing existing container...'
              docker rm welcome_page | Out-File -Append -FilePath C:\users\administrator\logs\deploy_log.txt

              Write-Host 'Pulling latest image...'
              docker pull ramuvchityala/welcome_page:latest | Out-File -Append -FilePath C:\users\administrator\logs\deploy_log.txt

              Write-Host 'Running new container...'
              docker run -d -p 80:80 --name welcome_page ramuvchityala/welcome_page:latest | Out-File -Append -FilePath C:\users\administrator\logs\deploy_log.txt

              Add-Content -Path C:\users\administrator\logs\deploy_log.txt -Value '[INFO] Deployment completed successfully.'
            } catch {
              Add-Content -Path C:\users\administrator\logs\deploy_log.txt -Value ('[ERROR] ' + $_.Exception.Message)
            }
          "
