name: CI/CD for Windows EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub (PowerShell)
      run: |
        echo $Env:DOCKER_PASSWORD | docker login -u $Env:DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/welcome_page:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/welcome_page:latest

    - name: Deploy to Windows EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        shell: powershell
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/welcome_page:latest
          docker stop web -ErrorAction SilentlyContinue
          docker rm web -ErrorAction SilentlyContinue
          docker run -d --name web -p 80:80 ${{ secrets.DOCKER_USERNAME }}/welcome_page:latest
