name: CI/CD for Windows IIS Container

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        run: |
          echo $Env:DOCKER_PASSWORD | docker login -u $Env:DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with version tag
        run: |
          docker build -t $Env:DOCKER_USERNAME/welcome_page:${{ github.run_number }} .
          docker tag $Env:DOCKER_USERNAME/welcome_page:${{ github.run_number }} $Env:DOCKER_USERNAME/welcome_page:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push Docker Images
        run: |
          docker push $Env:DOCKER_USERNAME/welcome_page:${{ github.run_number }}
          docker push $Env:DOCKER_USERNAME/welcome_page:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  pull-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy versioned image to Windows EC2 Step-1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          shell: powershell

          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/welcome_page:${{ github.run_number }} 

  stop-on-ec2:
    needs: pull-to-ec2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy versioned image to Windows EC2 Step-2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          shell: powershell

          script: |
            docker stop welcome_page 
  remove-from-ec2:
    needs: stop-on-ec2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy versioned image to Windows EC2 Step-3
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          shell: powershell

          script: |
            docker rm welcome_page

  run-on-ec2:
    needs: remove-from-ec2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy versioned image to Windows EC2 Step-4
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          shell: powershell

          script: |
            docker run -d -p 80:80 --name welcome_page ${{ secrets.DOCKER_USERNAME }}/welcome_page:${{ github.run_number }}

  cleanup-ec2:
    needs: run-on-ec2
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup and deploy versioned image to Windows EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          shell: pwsh
          run: |
            powershell -Command "docker images --format '{{.Repository}}:{{.Tag}}' | ForEach-Object { if ($_ -match ':(\d+)$' -and [int]$matches[1] -lt $env:GITHUB_RUN_NUMBER) { docker rmi $_ } }"